// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BandwidthScheduler.Server.DbModels;

public partial class Commitment
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int TeamId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public virtual ICollection<CommitmentNotification> CommitmentNotifications { get; set; } = new List<CommitmentNotification>();

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}