// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BandwidthScheduler.Server.DbModels;

public partial class CommitmentNotification
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CommitmentId { get; set; }

    public DateTime TimeStamp { get; set; }

    public bool Seen { get; set; }

    public virtual Commitment Commitment { get; set; }

    public virtual User User { get; set; }
}