// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BandwidthScheduler.Server.DbModels;

public partial class Password
{
    public int UserId { get; set; }

    public string Salt { get; set; }

    public string Hash { get; set; }

    public virtual User User { get; set; }
}