// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BandwidthScheduler.Server.DbModels;

public partial class Team
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Enabled { get; set; }

    public virtual ICollection<Commitment> Commitments { get; set; } = new List<Commitment>();

    public virtual ICollection<UserTeam> UserTeams { get; set; } = new List<UserTeam>();
}